### PR TITLE
add cv_bridge_javacv (java library).

### PR DESCRIPTION
**Pull request by talregev**
update ImageEncodings name to be appropriate for java style classes names (class start with capital letter).

check running with example android apps. (working).

### CODE REVIEW

**Comment by talregev** [comment]
@adamantivm 
I add cv_bridge_javacv.
When it approve and insert to rosjava_mvn_repo,
I will add to android_extra the rest of the library and examples apps from here:
https://github.com/talregev/android_cv_bridge

**Comment by adamantivm** [comment]
Looks interesting. Thank you @talregev ! I will try to at least build it to make sure that works and then merge and publish to maven. Stay tuned.

**Comment by talregev** [comment]
@adamantivm Thanks! I will add pull request to android_extra probably tomorrow.
And you can check my library with the example apps I will provide.
Also I write a wiki [here][2] access from [here][1], that can be modified.

[1]: http://wiki.ros.org/cv_bridge/Tutorials
[2]: http://wiki.ros.org/cv_bridge/Tutorials/Converting%20between%20ROS%20images%20and%20OpenCV%20images%20%28Android%20Java%29

**Comment by talregev** [comment]
there are two open_cv library. one is pure java (with javacv) and other one the original of opencv is android library. I make for both of them cv_bridge library that people can choose to use. for both there are pros and cons.

**Comment by adamantivm** [comment]
Sounds great @talregev . Feel free to link to your tutorials from [here](http://wiki.ros.org/android)

**Pull request merged**
